name: Test
on:
- pull_request
- push
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: joshvanl-yazbu
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix-shell --pure --run "go test -v --race ./cmd/... ./internal/..."
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: joshvanl-yazbu
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix-shell --pure --run "test -z $(gofmt -l -s .) || echo \"please run 'go fmt -s -w .'\""
    - run: nix-shell --pure --run "go vet -v ./..."
  e2e:
    needs:
    - unit
    - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: joshvanl-yazbu
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: nix-build nix/test.nix
