name: Test
on:
- pull_request
- push
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - run: nix flake check
    - run: nix-shell --pure --run "go test -v --race ./cmd/... ./internal/..."
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - run: nix flake check
    - run: nix-shell --pure --run "GOROOT=$(go env GOROOT) golangci-lint run -v --timeout 15m"
  e2e:
    needs:
    - unit
    - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - run: nix flake check
    - run: nix-build nix/test.nix
